---
title: "figs"
author: "Karissa Barthelson"
date: "2024-07-03"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
```{r}
library(cowplot)
library(ComplexHeatmap)
library(UpSetR)
library(gridExtra)
library(goseq)
library(tidytext)
```

# variables, functions + colours
```{r}
group_colours = 
  c("het_control" = "#74B3CE", 
    "het_iron" = "#172A3A", 
    "hom_control" = "#FF595E", 
    "hom_iron" = "#914024")

theme_kb <- function() { 
      theme_classic() %+replace%    #replace elements we want to change
    
    theme(
      
      #grid elements
      # panel.grid.major = element_blank(),    #strip major gridlines
      # panel.grid.minor = element_blank(),    #strip minor gridlines
      # axis.ticks = element_blank(),          #strip axis ticks
      
      #since theme_minimal() already strips axis lines, 
      #we don't need to do that again
      
      #text elements
      plot.title = element_text(             #title
                   #family = font,            #set font family
                   size = 18,                #set font size
                   face = 'bold',            #bold typeface
                   hjust = 0.5,                #left align
                   #vjust = 4
                   ),               #raise slightly
      
      plot.subtitle = element_text(          #subtitle
                   #family = font,            #font family
                   size = 14),               #font size
      
      plot.caption = element_text(           #caption
                   #family = font,            #font family
                   size = 9,                 #font size
                   hjust = 1),               #right align
      
      axis.title = element_text(             #axis titles
                  # family = font,            #font family
                   size = 10),               #font size
      
      axis.text = element_text(              #axis text
                  # family = font,            #axis famuly
                   size = 9),                #font size
      
      axis.text.x = element_text(            #margin for axis text
                    margin=margin(5, b = 10))
      
      #since the legend often requires manual tweaking 
      #based on plot content, don't define it here
    )
}

ggsavekb <- function(filename, width, height, scale){
  ggsave(
    filename = paste0("output/plots4paper/", filename), 
    width = width, height = height, units = "cm", scale = scale) 
  }

```
# Main Figures

### Fig. 3 - PCA
```{r}
ggarrange(
  logCPM %>% 
    t() %>% 
    prcomp() %>%
    autoplot(data = tibble(sample = rownames(.$x)) %>%
               left_join(x$samples),
             colour = "group", 
             shape = "sex",
             size = 4
    ) +
    scale_color_manual(
      values = group_colours
    ) +
    labs(
      title = "all samples"

    ) +
    theme_kb() +
    theme(
      aspect.ratio = 1, 
      legend.position = "bottom"
      ),
  
  logCPM.female %>% 
    t() %>% 
    prcomp() %>%
    autoplot(data = tibble(sample = rownames(.$x)) %>%
               left_join(x$samples),
             colour = "group", 
             shape = "sex",
             size = 4
    ) +
    scale_color_manual(
      values = group_colours
    ) +
    labs(
      title = "females"

    ) +
    theme_kb() +
    theme(
      aspect.ratio = 1, 
      legend.position = "bottom"
      ),
  
  logCPM.male %>% 
    t() %>% 
    prcomp() %>%
    autoplot(data = tibble(sample = rownames(.$x)) %>%
               left_join(x$samples),
             colour = "group", 
             shape = 17,
             size = 4
    ) +
    scale_color_manual(
      values = group_colours
    ) +
    labs(
      title = "males"
    ) +
    theme_kb() +
    theme(
      aspect.ratio = 1, 
      legend.position = "bottom"
      ),

  nrow = 1,
  common.legend = TRUE
  ) +
  ggsavekb(filename = "PCA.png", 
           width = 18, height = 7, scale = 1.5)
```

### Fig.3 - num of DEGs
```{r}
DEGs <- 
  toptables_cqn %>% 
  lapply(
    dplyr::filter, 
    DE == TRUE
  )%>%  
  lapply(extract2, "gene_id") %>% 
  fromList()


DEGs_females <- 
  toptables_cqn[names(toptables_cqn) %>% 
                  grepl(pattern = "female")] %>% 
  lapply(
    dplyr::filter, 
    DE == TRUE
  )%>%  
  lapply(extract2, "gene_id") %>% 
  set_names(str_remove_all(names(.), pattern = "_female")) %>% 
  fromList()


DEGs_males <- 
  toptables_cqn[names(toptables_cqn) %>% 
                  grepl(pattern = "_male")] %>% 
  lapply(
    dplyr::filter, 
    DE == TRUE
  )%>%  
  lapply(extract2, "gene_id") %>% 
  set_names(str_remove_all(names(.), pattern = "_male")) %>% 
  fromList()

upsets = list(
  all_comparisons  = upset(
    DEGs, 
    nsets = dim(DEGs)[2], 
    order.by = "freq", 
    set_size.show = TRUE, 
    text.scale = 2, 
    cutoff = 10),
    
    females = upset(
      DEGs_females, 
      nsets = dim(DEGs)[2], 
      order.by = "freq", 
      set_size.show = TRUE, 
      text.scale = 2
      
    ), 
    
    males = upset(
      DEGs_males, 
      nsets = dim(DEGs)[2], 
      order.by = "freq", 
      set_size.show = TRUE, 
      text.scale = 2
    )
  )
  
  
  for (v in names(upsets)) {
    print(upsets[[v]])
  grid.text(v, x = 0.65, y=0.97, gp = gpar(fontsize = 20))
  grid.edit('arrange', name = v)
  vp <- grid.grab()
  upsets[[v]] <- vp
}
grid.arrange(grobs = upsets, ncol = 3)


metadata <- tibble(
  sets = names(DEGs)
) %>% 
  mutate(
    sex = str_remove(sets,pattern = ".+_")
  )
```
```{r}
png("output/plots4paper/upsetDEGs.png", width = 30, height = 15, 
    units = "cm", res = 300, bg = NA)
par(omi = c(0,0,0,0), mgp = c(0,0,0), mar = c(0,0,0,0), family = "D")
upset(
    DEGs, 
    nsets = dim(DEGs)[2], 
    order.by = "freq", 
    set_size.show = TRUE, 
    text.scale = 2,
    set_size.scale_max = 1000,
    sets.x.label = "Number of\nDE genes", 
    mb.ratio = c(0.5, 0.5), 
    )
dev.off()    
```

```{r}
# add the names to the goseq file
mynames <- names(goseqResults)
goseqResults <- map2(goseqResults, mynames, ~.x %>% mutate(coef = .y))
 
goseqResults %>% 
  lapply(function(y){
    y %>% 
      left_join(goSummaries, by = c("category" = "gs_name")) %>% 
      dplyr::filter(ontology %in% c("CC", "MF")) %>% 
      head(5)
  }) %>% 
  bind_rows() %>% 
  mutate(sex = case_when(
    grepl(coef, pattern = "_male") ~ "male", 
    grepl(coef, pattern = "_female") ~ "female"), 
    
  category = str_replace_all(category, pattern = "_", replacement = " "),
  category = str_remove(category, pattern = "GO "), 
  category = str_wrap(category, width = 20), 
  category = reorder_within(category, -over_represented_pvalue, coef)
  ) %>% 
  
  ggplot(aes(x = -log10(over_represented_pvalue), 
             y = category,
             fill = FDR < 0.05)) +
  geom_col() +
  facet_wrap(~sex+coef, 
             nrow=2,
             scales = "free_y") +
  scale_fill_manual(values = c("grey50", "red")) +
  scale_y_reordered() +
  theme_kb() +
  theme(legend.position = "top", 
        text = element_text(size = 10)) +
  ggsavekb("GOoverrepPlot.png", width = 22, height = 7, scale = 1.7)
```


```{r}
interestingGOs <- goseqResults %>% 
  lapply(function(y){
    y %>% 
      left_join(goSummaries, by = c("category" = "gs_name")) %>% 
      dplyr::filter(ontology %in% c("CC", "MF")) %>% 
      head(10)
  }) %>% 
  bind_rows() %>% 
  .$category %>% 
  unique

goseqResults %>% 
  # lapply(function(y){
  #   y %>% 
  #     left_join(goSummaries, by = c("category" = "gs_name")) %>% 
  #     dplyr::filter(ontology %in% c("CC", "MF")) %>% 
  #     head(5)
  # }) %>% 
  bind_rows() %>% 
  dplyr::filter(category %in% interestingGOs) %>% 
  mutate(sex = case_when(
    grepl(coef, pattern = "_male") ~ "male", 
    grepl(coef, pattern = "_female") ~ "female"), 
  category = str_replace_all(category, pattern = "_", replacement = " "),
  category = str_remove(category, pattern = "GO "), 
  category = str_wrap(category, width = 20), 
  # category = reorder_within(category, -over_represented_pvalue, coef)
  ) %>% 
  ggplot(
    aes(x = coef, y = category)
  ) +
  geom_tile(
    aes(fill = -log10(over_represented_pvalue))
  ) +
  geom_label(
    aes(label = signif(FDR, 2))
  ) +
  facet_wrap(~sex, 
             scales = "free") +
  scale_fill_viridis_c() + 
  theme_kb() +
  theme(
    axis.text.x = element_text(
      angle = -45, vjust = 0.5, hjust = 0
    )
  )
```


# WGCNA
### dendrograms
```{r}
png("output/plots4paper/WGCNAdendrogramFEMS.png", 
    width = 12, height = 6, units = "cm", 
    res = 100)

plotDendroAndColors(
  geneTree.signed.females, 
  mergedColors.signed.females,
  "Modules",
  dendroLabels = FALSE, hang = 0.03,
  addGuide = F, guideHang = 0.05, ylim = c(1.0, 0.4),
  colorHeight = 0.5, 
  main = "Females", 
)
dev.off()
```

```{r}
png("output/plots4paper/WGCNAdendrogramMALES.png", 
    width = 12, height = 6, units = "cm", 
    res = 100)

plotDendroAndColors(
  geneTree.signed.males, 
  mergedColors.signed.males,
  "Modules",
  dendroLabels = FALSE, hang = 0.03,
  addGuide = F, guideHang = 0.05, 
  ylim = c(1.0, 0.4),
  colorHeight = 0.5, 
  main = "Males", 
)
dev.off()
```

## ME dendrograms
#### females
```{r}
module.order.fems <- moduleTraitCor.signed.females %>%
  #.[interesting.modules.females,] %>%
  as.data.frame() %>%
  dplyr::select(-1) %>%
  t() %>% 
  colnames(.)

colours.fems <- tibble(
  colname = module.order.fems, 
  colour = colname %>% str_remove(pattern = "^ME")
)

  names(colours.fems$colour) = colours.fems$colname

dcols = as.dist(1-cor(merge.signed.females$newMEs))
  
moduleTraitCor.signed.females %>%
  #.[interesting.modules.females,] %>%
  as.data.frame() %>%
  dplyr::select(-1) %>%
  as.matrix %>% 
  t() %>% 
  pheatmap::pheatmap(
    color = colorRampPalette(rev(brewer.pal(n = 7,
                                            name = "RdBu")))(100),
     #border_color = "white",
     #angle_col = 90,
    gaps_row = c(1,1,1),
    treeheight_row = 0,
     treeheight_col = 50,
     clustering_distance_cols = dcols,
     cluster_rows = T,
     number_color = "black",
     cellwidth = 25, cellheight = 20,
     fontsize = 12, legend = T,
    
     main = "Females", 
    
    display_numbers = moduleTraitPValue.signed.females %>%
      #.[interesting.modules.females,] %>%
      dplyr::select(-1, -module) %>%
      t %>%
      signif(1), 
    
    annotation_col = data.frame(
      module = colnames(.)
    ) %>% 
      set_rownames(value = .$module), 
    
    annotation_colors = list(module = colours.fems$colour), 
    
    file = "output/plots4paper/WGCNA_modules_females.png"
  )
```

#### males
```{r}
module.order.males <- moduleTraitCor.signed.males %>%
  #.[interesting.modules.females,] %>%
  as.data.frame() %>%
  dplyr::select(-1) %>%
  t() %>% 
  colnames(.)

colours.males <- tibble(
  colname = module.order.males, 
  colour = colname %>% str_remove(pattern = "^ME")
)

  names(colours.males$colour) = colours.males$colname

dcols = as.dist(1-cor(merge.signed.males$newMEs))
  
moduleTraitCor.signed.males %>%
  #.[interesting.modules.females,] %>%
  as.data.frame() %>%
  dplyr::select(-1) %>%
  as.matrix %>% 
  t() %>% 
  pheatmap::pheatmap(
    color = colorRampPalette(rev(brewer.pal(n = 7,
                                            name = "RdBu")))(100),
     #border_color = "white",
     #angle_col = 90,
    treeheight_row = 0,
     treeheight_col = 50,
     clustering_distance_cols = dcols,
     cluster_rows = F,
     number_color = "black",
     cellwidth = 25, cellheight = 20,
     fontsize = 12, legend = T,
    
     main = "Males", 
    
    display_numbers = moduleTraitPValue.signed.males %>%
      #.[interesting.modules.females,] %>%
      dplyr::select(-1, -module) %>%
      t %>%
      signif(1), 
    
    annotation_col = data.frame(
      module = colnames(.)
    ) %>% 
      set_rownames(value = .$module), 
    
    annotation_colors = list(module = colours.males$colour), 
    
    file = "output/plots4paper/WGCNA_modules_males.png"
  )
```

# enrichment of modules 

```{r}
# a function to grab pval from the association w/ genotype
p1 <- ggarrange(merge.signed.females$newMEs %>% 
  as.data.frame() %>% 
  rownames_to_column("fish_id") %>% 
  dplyr::select(fish_id, MEroyalblue) %>% 
  as_tibble %>% 
  left_join(x.females$samples) %>% 
  pivot_longer(names_to = "module", values_to = "ME_value", starts_with("ME")) %>% 
  ggplot(aes(x = treatment, y = ME_value, colour = genotype)) +
    geom_boxplot() +
  scale_color_manual(
      values = c("grey30", "orange")
    ) +  
  labs(
    title = paste("royalblue module -", 
                  length(genesInModuleList.signed.females$royalblue), 
                  "genes"),
    subtitle = paste("Genotype: p =", 
                moduleTraitPValue.signed.females["MEroyalblue","genotypehom"] %>% 
                  signif(2), 
                "\nGenotype x treatment: p = ", 
                moduleTraitPValue.signed.females["MEroyalblue","genotypehom:treatment10 µg Fe-citrate"] %>% signif(2)
    )
    ), 
  
  upsetplot(merged.moduls.female.signed.enrichment.res.all$royalblue, n = 10) + 
    ggtitle("Enriched GO terms in royalblue module")
) 

p2 <- 
  
  ggarrange(
  merge.signed.females$newMEs %>% 
  as.data.frame() %>% 
  rownames_to_column("fish_id") %>% 
  dplyr::select(fish_id, MEblue) %>% 
  as_tibble %>% 
  left_join(x.females$samples) %>% 
  pivot_longer(names_to = "module", 
               values_to = "ME_value", starts_with("ME")
               ) %>%
  ggplot(
    aes(x = treatment, y = ME_value, colour = genotype)
    ) +
  geom_boxplot() +
    scale_color_manual(
      values = c("grey30", "orange")
    ) + 
      labs(
    title = paste0("Blue module - ",
           length(genesInModuleList.signed.females$blue), 
                 " coexpressed genes"),
    subtitle = paste("Genotype: p =", 
                moduleTraitPValue.signed.females["MEblue","genotypehom"] %>% 
                  signif(2), 
                "\nGenotype x treatment: p = ", 
                moduleTraitPValue.signed.females["MEblue","genotypehom:treatment10 µg Fe-citrate"] %>% signif(2)
    )
    ), 

  upsetplot(merged.moduls.female.signed.enrichment.res$blue) +
    labs(
      title = "Upset plot showing overlap of genes driving the enrichment of GO terms")
) 

p1 / p2
```





```{r}
library(ggraph)
library(igraph)
library(ComplexHeatmap)


# create a data frame giving the hierarchical structure of your individuals
d1=data.frame(from="origin", to=paste("group", seq(1,10), sep=""))
d2=data.frame(from=rep(d1$to, each=10), to=paste("subgroup", seq(1,100), sep="_"))
edges=rbind(d1, d2)

nodes <- read_delim("output/WGCNA/female-cytoscape_2_nodes.csv", delim = "\t")


edges <- read_tsv("output/WGCNA/female-cytoscape_2_edges.csv")
colnames(edges) <- "temp"
edges  # Split name column into firstname and last name
edges[c('from', 'to', "weight")] <- str_split_fixed(edges$temp, "\t", 3)

edges %<>% 
  dplyr::select(-temp) %>% 
  mutate(
    weight = str_remove(weight, "\tundirected\tNA\tNA")
  )
mygraph <- graph_from_data_frame( edges )

ggraph(mygraph, layout = "treemap") 
  geom_edge_diagonal() +
  geom_node_point() +
  theme_void()
```


```{r}
library(circlize)
library(dendsort)

hc = hclust(dist(merge.signed.females$newMEs), method = "single")

MEDiss.signed.females
geneTree.signed.females

col_fun_viridis = colorRamp2(c(-2, 0, 2), viridis_pal(begin = 0, end = 1)(7))
col_fun_rdbu <- colorRamp2(c(-2, 0, 2), c("blue", "white", "red"))

pvals.matrix.genotreat.fems <- moduleTraitPValue.signed.females %>% 
  dplyr::select(-module, -`(Intercept)`) %>% 
  set_colnames(
    c("Geno", "Treat", "Geno x Treat")
  ) 

rownames(pvals.matrix.genotreat.fems) %<>% 
  str_remove(pattern = "ME")

WGCNAcols = merge.signed.females$colors %>% unique
names(WGCNAcols) =   WGCNAcols
WGCNAcols

wgcna.cols.mat <- data.frame(
  col = WGCNAcols
)
```


```{r}
circos.clear()
circos.par(gap.after=c(40), start.degree=(110), track.height= c(0.05))	
circos.heatmap(wgcna.cols.mat,col=WGCNAcols, 
               rownames.side="outside", rownames.cex=1)
circos.par(gap.after=c(40), start.degree=(110), track.height= c(0.1))	
circos.heatmap(
  pvals.matrix.genotreat.fems, 
               col=col_fun1, 
  bg.border="black", 
  bg.lwd=1
  )
circos.track(
  track.index = get.current.track.index(), 
  panel.fun = function(x, y) {
        cn = colnames(pvals.matrix.genotreat.fems)
        n = length(cn)
        circos.text(rep(CELL_META$cell.xlim[2], n) + convert_x(1, "mm"), 
            n - 1:n + 0.5, cn, 
            cex = 1, adj = c(0, 0.5), facing = "inside")
}, bg.border = NA)


```




# Supp figs

### num fish per group
```{r}
x$samples %>% 
  mutate(genotreatsex = paste0(group, "_", sex)) %>% 
  ggplot(
    aes(x = group)
  ) +
  geom_bar(
    aes(fill = sex)
    ) +
  theme_bw() +
  scale_y_continuous(
    breaks = 1:10
  )
```

### PCA by sex

```{r}
  
  logCPM %>% 
    t() %>% 
    prcomp() %>%
    autoplot(data = tibble(sample = rownames(.$x)) %>%
               left_join(x$samples),
             colour = "sex", 
             size = 4
    ) +
    labs(
    ) +
    theme_kb() +
    theme(
      aspect.ratio = 1, 
      legend.position = "bottom"
      )
```

